### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Blasir0** [MaciaEze/Mercado-Liebre-DH#1]
1. Header => CUMPLE
    Main => CUMPLE
    Footer => CUMPLE (Observación: "Envios gratis desde $1.999" debería ser "Envío gratis desde $2.500" y el mensaje de "Copyright © Digital House Alumno 1989-2022 MercadoLiebre S.R.L." debería ser "Copyright © 1999-2022 MercadoLiebre S.R.L.")
2. CUMPLE (Observación:  Tiene padding 10px en lugar de margin-bottom de 10px y el tamaño de los iconos cambia a 2.5 en modo desktop)
3. CUMPLE
4. CUMPLE
5. CUMPLE
6. CUMPLE
7. CUMPLE
8. CUMPLE
9. Creó una página visualmente prolija y agradable a la vista. Cumple con los requisitos y es fácil de entender y usar. Se esmeró en darle al botón de seleccionar foto de perfil un estilo más vistoso que el que viene predeterminado. Además, logro fijar el header para que éste se mantenga en la pantalla al descender agregandole una mayor facilidad a la navegación.
10. Podría mejorar la animación del camión ya que éste gira 45 grados en lugar de 90, y para las resoluciones menores el logo y la barra de búsqueda deberían ocupar cada una el 50% del ancho de la línea y el texto de "Comprá en cuotas y sin tarjeta de crédito" debería estar centrado. También creo que el tamaño de la fuente de los textos en el "header" en la version "Desktop" podría ser un poco más grande para que sea mas agradable a la vista.

**Comment by MaciaEze** [comment]
Se corrigio el texto del footer.
Sobre el padding y el margin-botton y el tamaño del icono es por el responsive.
